### 센서에서 들어오는 데이터 확인
POST http://localhost:10245/rule_engine/data
Content-Type: application/json

{
  "gateway_id": "gateway-001",
  "sensor_id": "sensor-001",
  "type": "temperature",
  "value": 41.00,
  "timestamp": 1747879909160
}
